default: &default
  adapter: postgresql
  encoding: unicode
  database: recipes
  pool: 50
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: recipes

production:
  <<: *default
  database: recipes-prod

