default: &default
  adapter: postgresql
  encoding: unicode
  database: recipes
  pool: 50
  host: ec2-184-73-196-82.compute-1.amazonaws.com
  username: ranhoqvjdczsxm
  password: tSYu7TBsMCobIT0BsmlThvk-tX

development:
  <<: *default
  database: d8beh3jg50d5q4

production:
  <<: *default
  database: postgresql-amorphous-52836

